package com.mba.drc.medicalapp;

	/* This class represents a collection of non-mutually exclusive days

	 this file was generated by a script */
	 
	class DayGroup{
	private boolean mSunday;
	private boolean mMonday;
	private boolean mTuesday;
	private boolean mWednesday;
	private boolean mThursday;
	private boolean mFriday;
	private boolean mSaturday;

	DayGroup(){
		mSunday = false;
		mMonday = false;
		mTuesday = false;
		mWednesday = false;
		mThursday = false;
		mFriday = false;
		mSaturday = false;
	}
	DayGroup(int dnum){
		mSunday = ((dnum>>0) & 0x01) != 0;
		mMonday = ((dnum>>1) & 0x01) != 0;
		mTuesday = ((dnum>>2) & 0x01) != 0;
		mWednesday = ((dnum>>3) & 0x01) != 0;
		mThursday = ((dnum>>4) & 0x01) != 0;
		mFriday = ((dnum>>5) & 0x01) != 0;
		mSaturday = ((dnum>>6) & 0x01) != 0;
	}

	boolean sunday(){return mSunday;}
	boolean monday(){return mMonday;}
	boolean tuesday(){return mTuesday;}
	boolean wednesday(){return mWednesday;}
	boolean thursday(){return mThursday;}
	boolean friday(){return mFriday;}
	boolean saturday(){return mSaturday;}

	void setSunday(boolean s){ mSunday=s; }
	void setMonday(boolean s){ mMonday=s; }
	void setTuesday(boolean s){ mTuesday=s; }
	void setWednesday(boolean s){ mWednesday=s; }
	void setThursday(boolean s){ mThursday=s; }
	void setFriday(boolean s){ mFriday=s; }
	void setSaturday(boolean s){ mSaturday=s; }
	int toInt(){
		int rv = 0;
		rv |= (mSunday ? (1<<0) : 0);
		rv |= (mMonday ? (1<<1) : 0);
		rv |= (mTuesday ? (1<<2) : 0);
		rv |= (mWednesday ? (1<<3) : 0);
		rv |= (mThursday ? (1<<4) : 0);
		rv |= (mFriday ? (1<<5) : 0);
		rv |= (mSaturday ? (1<<6) : 0);
		return rv;
	}
	public String toString(){
		String rv = "";
		if(toInt() == 0x7F) return "Everyday";
		else if(toInt() == 0x3E) return "Weekdays";
		else if(toInt() == 0x41) return "Weekends";
		if(mSunday) rv += "Su";
		if(mMonday) rv += "M";
		if(mTuesday) rv += "T";
		if(mWednesday) rv += "W";
		if(mThursday) rv += "H";
		if(mFriday) rv += "F";
		if(mSaturday) rv += "S";
		return rv;
	}
}
