/* This class was generated by script */
package com.mba.drc.medicalapp;
public class DayGroup {
    private boolean mSunday;
    private boolean mMonday;
    private boolean mTuesday;
    private boolean mWednesday;
    private boolean mThursday;
    private boolean mFriday;
    private boolean mSaturday;

    public DayGroup(){
        mSunday = false;
        mMonday = false;
        mTuesday = false;
        mWednesday = false;
        mThursday = false;
        mFriday = false;
        mSaturday = false;
    }

    boolean sunday(){return mSunday;}
    boolean monday(){return mMonday;}
    boolean tuesday(){return mTuesday;}
    boolean wednesday(){return mWednesday;}
    boolean thursday(){return mThursday;}
    boolean friday(){return mFriday;}
    boolean saturday(){return mSaturday;}

    void setSunday(boolean s){ mSunday=s; }
    void setSunday(){ mSunday=true; }
    void setMonday(boolean s){ mMonday=s; }
    void setMonday(){ mMonday=true; }
    void setTuesday(boolean s){ mTuesday=s; }
    void setTuesday(){ mTuesday=true; }
    void setWednesday(boolean s){ mWednesday=s; }
    void setWednesday(){ mWednesday=true; }
    void setThursday(boolean s){ mThursday=s; }
    void setThursday(){ mThursday=true; }
    void setFriday(boolean s){ mFriday=s; }
    void setFriday(){ mFriday=true; }
    void setSaturday(boolean s){ mSaturday=s; }
    void setSaturday(){ mSaturday=true; }
    int toInt(){
        int rv = 0;
        rv |= (mSunday ? (1<<0) : 0);
        rv |= (mMonday ? (1<<1) : 0);
        rv |= (mTuesday ? (1<<2) : 0);
        rv |= (mWednesday ? (1<<3) : 0);
        rv |= (mThursday ? (1<<4) : 0);
        rv |= (mFriday ? (1<<5) : 0);
        rv |= (mSaturday ? (1<<6) : 0);
        return rv;
    }
}

