#!/usr/bin/env python3

days = ["sunday", "monday", "tuesday","wednesday", "thursday","friday", "saturday"]

print("/* This class was generated by script */")
print("public class DayGroup {")
for day in days:
	print(f"\tprivate boolean m{day.title()};")
print("")
print("\tpublic DayGroup(){")
for day in days:
	print(f"\t\tm{day.title()} = false;")
print("\t}")
print("")
for day in days:
	print(f"\tpublic boolean {day}(){{return m{day.title()};}}")
print("");
for day in days:
	print(f"\tpublic void set{day.title()}(boolean s){{ m{day.title()}=s; }}")
	print(f"\tpublic void set{day.title()}(){{ m{day.title()}=true; }}")

print("}\n")
